import XCTest
@testable import URRegistry

final class URRegistryTests: XCTestCase {
    func testURDecoderResult() {
        let ur = "UR:CRYPTO-HDKEY/PTAOWKAXHDCLAOREGSNYCEIHDYCNQDPEPSIELYRTHFQZDWGYFPISFLTSUTUYCSDRVDREWSLYWDHHPDAAHDCXGMCTGAMNCKGATDWSEEOXEHHNGMSTFGSRCEJNJTWYGWBDZSJZDYLRLBINFWFGVWJPAHTAADEHOEADCSFNAOAEAMTAADDYOTADLNCSDWYKCSFNYKAEYKAOCYJOKBWEJZAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYGUBKLBMWASISGRIHKKJKJYJLJTIHBKJOHSIAIAJLKPJTJYDMJKJYHSJTIEHSJPIECLRECMSN"
        let sut = URRegistry.shared
        
        sut.getHDKey(from: ur)
    }
}
